export default {
	WelcomeScreen: 'WelcomeScreen',

	BottomTabs: 'BottomTabs',
	LoggedStack: 'LoggedStack',
	NotLoggedStack: 'NotLoggedStack',

	HomeStack: 'HomeStack',
	HomeScreen: 'HomeScreen',
	CartScreen: 'CartScreen',

	SearchStack: 'SearchStack',
	SearchScreen: 'SearchScreen',
	SearchCartScreen: 'SearchCartScreen',

	ChatStack: 'ChatStack',
	WelcomeChatScreen: 'WelcomeChatScreen',
	OfflineContactSupportScreen: 'OfflineContactSupportScreen',
	ChatScreen: 'ChatScreen',
	ShareChatScreen: 'ShareChatScreen',
	NewCallScreen: 'NewCallScreen',
	NewChatScreen: 'NewChatScreen',
	CameraScreen: 'CameraScreen',
	VideoCallScreen: 'VideoCallScreen',
	InvitationsScreen: 'InvitationsScreen',
	SnapfoodMapScreen: 'SnapfoodMapScreen',
	StorySettingScreen: 'StorySettingScreen',
	SnapfoodMapSettingsScreen: 'SnapfoodMapSettingsScreen',
	MyFriendsScreen: 'MyFriendsScreen',
	MyContacts: 'MyContacts',
	SnapfoodersScreen: 'SnapfoodersScreen',
	SnapfooderScreen: 'SnapfooderScreen',
	CourierScreen: 'CourierScreen',
	NewGroupScreen: 'NewGroupScreen',
	CreateGroupScreen: 'CreateGroupScreen',
	MessagesScreen: 'MessagesScreen',
	LocationPickupScreen: 'LocationPickupScreen',
	LocationMsgScreen: 'LocationMsgScreen',
	ChooseFriendsScreen: 'ChooseFriendsScreen',
	ForwardScreen: 'ForwardScreen',
	StoryPreviewScreen: 'StoryPreviewScreen',
	GiftUserPickScreen: 'GiftUserPickScreen',

	OrdersStack: 'OrdersStack',
	OrdersScreen: 'OrdersScreen',
	OrdersCartScreen: 'OrdersCartScreen',

	ProfileStack: 'ProfileStack',
	ProfileScreen: 'ProfileScreen',
	PhoneVerificationScreen: 'PhoneVerificationScreen',
	EditPhoneScreen: 'EditPhoneScreen',
	ChangePasswordScreen: 'ChangePasswordScreen',
	DeleteAccountScreen: 'DeleteAccountScreen',
	FavouritesScreen: 'FavouritesScreen',
	AddressesScreen: 'AddressesScreen',
	BlogScreen: 'BlogScreen',
	BlogDetailsScreen: 'BlogDetailsScreen',
	BlogFilterScreen: 'BlogFilterScreen',
	PromotionsScreen: 'PromotionsScreen',
	VendorPromotionsScreen: 'VendorPromotionsScreen',
	SnapfoodPromotionsScreen: 'SnapfoodPromotionsScreen',
	StudentVerifyScreen: 'StudentVerifyScreen',
	LoginScreen: 'LoginScreen',
	RegisterScreen: 'RegisterScreen',
	OnboardingScreen: 'OnboardingScreen',
	ForgotScreen: 'ForgotScreen',
	ResetPassScreen: 'ResetPassScreen',
	ResetPassDoneScreen: 'ResetPassDoneScreen',
	AlmostDoneScreen: 'AlmostDoneScreen',
	LocationSetupScreen: 'LocationSetupScreen',
	FilterScreen: 'FilterScreen',
	VendorScreen: 'VendorScreen',
	VendorLocationScreen: 'VendorLocationScreen',
	FoodScreen: 'FoodScreen',
	PastOrderScreen: 'PastOrderScreen',
	NewAddressScreen: 'NewAddressScreen',
	AddressMapScreen: 'AddressMapScreen',
	CartPaymentScreen: 'CartPaymentScreen',
	CartSplitScreen: 'CartSplitScreen',
	SplitOrderScreen: 'SplitOrderScreen',
	CartSplitRequestScreen: 'CartSplitRequestScreen',
	SplitsHistScreen: 'SplitsHistScreen',
	SplitOrderNotuserScreen: 'SplitOrderNotuserScreen',
	OrderSummScreen: 'OrderSummScreen',
	OrderSummPayCard: 'OrderSummPayCard',
	OrderFilterScreen: 'OrderFilterScreen',
	TrackOrderScreen: 'TrackOrderScreen',
	OrderReviewScreen: 'OrderReviewScreen',
	ScantoPay: 'ScantoPay',
	OrderHelp: 'OrderHelp',
	OrderFaqs: 'OrderFaqs',
	OrderSupport: 'OrderSupport',
	SettingScreen: 'SettingScreen',
	WalletScreen: 'WalletScreen',
	DepositCardScreen: 'DepositCardScreen',
	DepositSuccessScreen: 'DepositSuccessScreen',
	TransferScreen: 'TransferScreen',
	TransferDetailsScreen: 'TransferDetailsScreen',
	PickFriendsScreen: 'PickFriendsScreen',
	CashbackOrdersScreen: 'CashbackOrdersScreen',
	InviteScreen: 'InviteScreen',
	EarnScreen: 'EarnScreen',
	InvitationHistScreen: 'InvitationHistScreen',
	InvitationReferralsHistScreen: 'InvitationReferralsHistScreen',
	InvitationDetailsScreen: 'InvitationDetailsScreen',
	InvitationFriendsScreen: 'InvitationFriendsScreen',
	InvitationSnapfoodersScreen: 'InvitationSnapfoodersScreen',
	ConfirmIdentityScreen: 'ConfirmIdentityScreen',
	PaymentMethodsScreen: 'PaymentMethodsScreen',
	DepositTransferHistScreen: 'DepositTransferHistScreen',
	NewCardScreen: 'NewCardScreen',
	ProfileEditScreen: 'ProfileEditScreen',
	SnapfoodersSplitScreen: 'SnapfoodersSplitScreen',
	GalleryScreen: 'GalleryScreen',
	ProfileInterestScreen: 'ProfileInterestScreen',
	GallerySettingScreen: 'GallerySettingScreen',
	InterestSettingScreen: 'InterestSettingScreen',
	BioSettingScreen: 'BioSettingScreen',
	GetPromoScreen: 'GetPromoScreen',
	PromosCalendarScreen: 'PromosCalendarScreen',
	ScanQRcodeScreen: 'ScanQRcodeScreen',
	MembershipScreen: 'MembershipScreen',
	MembershipInfoScreen: 'MembershipInfoScreen',
	ChangeMembershipPlan: 'ChangeMembershipPlan',
	MembershipFaqs: 'MembershipFaqs',

	AskContactsScreen: 'AskContactsScreen',
	ContactsScreen: 'ContactsScreen',

	EditNameScreen: 'EditNameScreen',
	ReportFeedbackScreen: 'ReportFeedbackScreen',
	ReferralCodeInputScreen: 'ReferralCodeInputScreen'
};

export const headerLessRoutes = [
	'LoginScreen',
	'RegisterScreen',
	'PhoneVerificationScreen',
	'EditPhoneScreen',
	'SearchScreen',
	'RaportoScreen',
];

export const bottomLessRoutes = [
	'LoginScreen',
	'RegisterScreen',
	'PhoneVerificationScreen',
	'EditPhoneScreen',
	'CartScreen',
	'SearchCartScreen',
	'OrdersCartScreen',
];
