export const APP = {
	SAFE_AREA_DIMENSIONS: 'SAFE_AREA_DIMENSIONS',
	SET_UNREVIEWED_ORDER: 'SET_UNREVIEWED_ORDER',
	CLOSE_REVIEW_MODAL: 'CLOSE_REVIEW_MODAL',

	GET_VENDORS_REQUEST: 'GET_VENDORS_REQUEST',
	GET_VENDORS_SUCCESS: 'GET_VENDORS_SUCCESS',
	GET_VENDORS_ERROR: 'GET_VENDORS_ERROR',
	UPDATE_VENDORS: 'UPDATE_VENDORS',

	GET_FEATURE_BLOCKS_REQUEST: 'GET_FEATURE_BLOCKS_REQUEST',
	GET_FEATURE_BLOCKS_SUCCESS: 'GET_FEATURE_BLOCKS_SUCCESS',
	GET_FEATURE_BLOCKS_ERROR: 'GET_FEATURE_BLOCKS_ERROR',

	GET_ADDRESSES_REQUEST: 'GET_ADDRESSES_REQUEST',
	GET_ADDRESSES_SUCCESS: 'GET_ADDRESSES_SUCCESS',
	GET_ADDRESSES_ERROR: 'GET_ADDRESSES_ERROR',
	UPDATE_ADDRESSES: 'UPDATE_ADDRESSES',

	DELETE_ADDRESSES_REQUEST: 'DELETE_ADDRESSES_REQUEST',
	DELETE_ADDRESSES_SUCCESS: 'DELETE_ADDRESSES_SUCCESS',
	DELETE_ADDRESSES_ERROR: 'DELETE_ADDRESSES_ERROR',

	GET_FAVOURITES_REQUEST: 'GET_FAVOURITES_REQUEST',
	GET_FAVOURITES_SUCCESS: 'GET_FAVOURITES_SUCCESS',
	GET_FAVOURITES_ERROR: 'GET_FAVOURITES_ERROR',

	CHANGE_FAVORITE_REQUEST: 'CHANGE_FAVORITE_REQUEST',
	CHANGE_FAVORITE_SUCCESS: 'CHANGE_FAVORITE_SUCCESS',
	CHANGE_FAVORITE_ERROR: 'CHANGE_FAVORITE_ERROR',

	SORT_VENDORS_BY_NAME: 'SORT_VENDORS_BY_NAME',
	SORT_VENDORS_BY_POPULARITY: 'SORT_VENDORS_BY_POPULARITY',
	SORT_VENDORS_BY_LOCATION: 'SORT_VENDORS_BY_LOCATION',
	APPLY_LOCATION: 'APPLY_LOCATION',
	APPLY_LOCATION_GEO: 'APPLY_LOCATION_GEO',
	CHECK_LOCATION: 'CHECK_LOCATION',
	RESET_BACK_TO_PARAM: 'RESET_BACK_TO_PARAM',
	FILL_CLOSED_MODAL_DATA: 'FILL_CLOSED_MODAL_DATA',
	RESET_CLOSED_MODAL_DATA: 'RESET_CLOSED_MODAL_DATA',

	GET_LAST_UNREVIEWED_ORDER_REQUEST: 'GET_LAST_UNREVIEWED_ORDER_REQUEST',
	GET_LAST_UNREVIEWED_ORDER_SUCCESS: 'GET_LAST_UNREVIEWED_ORDER_SUCCESS',
	GET_LAST_UNREVIEWED_ORDER_ERROR: 'GET_LAST_UNREVIEWED_ORDER_ERROR',

	SET_ADDRESS: 'SET_ADDRESS',

	GET_BANNERS: 'GET_BANNERS',
	GET_BANNERS_ERROR: 'GET_BANNERS_ERROR',
	GET_BANNERS_SUCCESS: 'GET_BANNERS_SUCCESS',
	SEND_BANNER_CLICKED: 'SEND_BANNER_CLICKED',

	SET_HASLOCATION_FLAG: 'SET_HASLOCATION_FLAG',

	LOGGED_IN: 'APP/LOGGED_IN',
	SEEN_ONBOARD: 'APP/SEEN_ONBOARD',
	USER_LOGGED_OUT: 'APP/USER_LOGGED_OUT',
	SET_USER_DATA: 'APP/SET_USER_DATA',
	SET_HAS_VERIFIED_PHONE: 'APP/SET_HAS_VERIFIED_PHONE',
	SET_SKIP_REFERRAL_CODE_INPUT_VIEW : 'APP/SET_SKIP_REFERRAL_CODE_INPUT_VIEW',
	SET_LOCATION_DATA: 'APP/SET_LOCATION_DATA',
	SET_NEED_LOGIN: 'APP/SET_NEED_LOGIN',

	SHOW_ORDER_STATUS_MODAL: 'APP/SHOW_ORDER_STATUS_MODAL',
	SET_ACTIVE_SCREEN_FROM_PUSH: 'APP/SET_ACTIVE_SCREEN_FROM_PUSH',

	SET_SHARED_INFORMATION: 'APP/SET_SHARED_INFORMATION',
	REMOVE_SHARED_INFORMATION: 'APP/REMOVE_SHARED_INFORMATION',

	SET_HOME_SCROLLER : 'APP/SET_HOME_SCROLLER',

	SET_VENDOR_IDS_TMP: 'APP/SET_VENDOR_IDS_TMP',

	// DYNAMIC-LINKS
	SET_LINKED_REFFERAL_CODE: 'SET_LINKED_REFFERAL_CODE',
	REMOVE_LINKED_REFFERAL_CODE: 'REMOVE_LINKED_REFFERAL_CODE',

	//CHAT
	SEND_MESSAGE: 'SEND_MESSAGE',
	ENTER_CHAT: 'ENTER_CHAT',
	INIT_CHAT_ROOM: 'INIT_CHAT_ROOM',
	INIT_CHAT_ROOM_STARTED: 'INIT_CHAT_ROOM_STARTED',
	CHAT_ROOM_EXIST: 'CHAT_ROOM_EXIST',
	INIT_CHAT_ROOM_SUCCESS: 'INIT_CHAT_ROOM_SUCCESS',
	INIT_CHAT_ROOM_ERROR: 'INIT_CHAT_ROOM_ERROR',
	NEW_MESSAGE_ARRIVED: 'NEW_MESSAGE_ARRIVED',
	MESSAGE_IS_MODIFIED: 'MESSAGE_IS_MODIFIED',
	SET_MESSAGES_SEEN: 'SET_MESSAGES_SEEN',
	BACK_TO_CHAT: 'BACK_TO_CHAT',

	INIT_CHANNEL_SUCCESS: 'INIT_CHANNEL_SUCCESS',
	SET_CHANNELS: 'SET_CHANNELS',
	SET_CHANNELS_LOADING: 'SET_CHANNELS_LOADING',
	SET_CALL_CHANNELS: 'SET_CALL_CHANNELS',
	SET_OPEN_STORY_IMG_PICK_MODAL: 'SET_OPEN_STORY_IMG_PICK_MODAL',

	REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
	UPDATE_CART: 'UPDATE_CART',

	RESET_CART: 'RESET_CART',

	SET_FAVOURITES: 'SET_FAVOURITES',
	SET_ALL_FAVOURITES: 'SET_ALL_FAVOURITES',

	SET_ADDRESSES: 'SET_ADDRESSES',
	DELETED_ADDRESS: 'DELETED_ADDRESS',
	ADDED_ADDRESS: 'ADDED_ADDRESS',

	SET_DEFAULT_ORDERS_TAB: 'SET_DEFAULT_ORDERS_TAB',

	// CART
	ADD_ITEM_CART: 'ADD_ITEM_CART',
	REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
	SET_CART_SPLIT: 'SET_CART_SPLIT',

	SET_CUTLERY_CART: 'SET_CUTLERY_CART',
	SET_COMMENT_CART: 'SET_COMMENT_CART',
	SET_COUPON_CART: 'SET_COUPON_CART',
	SET_PRICE_CART: 'SET_PRICE_CART',
	SET_DELIVERY_INFO_CART: 'SET_DELIVERY_INFO_CART',
	SET_PAYMENT_INFO_CART: 'SET_PAYMENT_INFO_CART',

	UPDATE_CART_ITEMS: 'UPDATE_CART_ITEMS',
	CLEAR_CART: 'CLEAR_CART',
	SET_VENDOR_CART: 'SET_VENDOR_CART',
	SET_ORDER_FOR: 'SET_ORDER_FOR',
	SET_CONFIRM_LEGAL_AGE: 'SET_CONFIRM_LEGAL_AGE',
	SET_DEFAULT_DELIVERY_ADDRESS: 'SET_DEFAULT_DELIVERY_ADDRESS',

	// Global
	SET_INIT_HOME_TAB: 'set_init_home_tab',
	SET_HOMETAB_NAVIGATION: 'set_hometab_navigation',
	TMP_PASS_CHANGED: 'pass_changed',
	TMP_ADDR_PICKED: 'location_address_picked',
	TMP_SET_FOOD: 'TMP_SET_FOOD',
	TMP_SET_ORDER: 'TMP_SET_ORDER',
	TMP_SET_CUR_PLAYING_VIDEO_STORY: 'TMP_SET_CUR_PLAYING_VIDEO_STORY',
	SET_VENDOR_FILTER: 'set_vendor_filter',
	SET_VENDOR_SORT: 'set_vendor_sort',
	SET_ORDERS_FILTER: 'set_orders_filter',
	SET_LANG: 'SET_LANG',
	SET_PROFILE_BLOG_FILTER: 'SET_PROFILE_BLOG_FILTER',
	SET_BLOG_CATEGORIES: 'SET_BLOG_CATEGORIES',
	SET_CONTACTS: 'SET_CONTACTS',
	SET_SHOW_CONTACTS_MODAL: 'SET_SHOW_CONTACTS_MODAL',
	SET_SHOW_REMIND_EARNINVITE_MODAL: 'SET_SHOW_REMIND_EARNINVITE_MODAL',
	SET_SHOW_INVITE_CONTACTS_FRIEND_MODAL: 'SET_SHOW_INVITE_CONTACTS_FRIEND_MODAL',
	SET_ASKED_CONTACTS_PERMISSION: 'SET_ASKED_CONTACTS_PERMISSION',
	SET_ASKED_INTERESTS: 'SET_ASKED_INTERESTS',
	SET_SHOW_INVITE_MUTUAL_FRIEND_MODAL: 'SET_SHOW_INVITE_MUTUAL_FRIEND_MODAL',
	SET_SHOW_REMIND_REFERRAL_MODAL: 'SET_SHOW_REMIND_REFERRAL_MODAL',
	SET_SHOW_ORDER_NOW_MODAL: 'SET_SHOW_ORDER_NOW_MODAL',

	SET_INVITE_PICKED_USER: 'SET_INVITE_PICKED_USER',
	SET_GIFT_ORDER_PICKED_USER : 'SET_GIFT_ORDER_PICKED_USER',
	SET_INVITATION_REWARDS: 'SET_INVITATION_REWARDS',
	SET_REFERRALS_REWARDS: 'SET_REFERRALS_REWARDS',
	SET_INVITATION_TIMER_SETTING: 'SET_INVITATION_TIMER_SETTING',
	SET_BALANCE_TRANSFER_PICKED_USER : 'SET_BALANCE_TRANSFER_PICKED_USER',
	
	SET_MEMBERSHIP_SETTING: 'SET_MEMBERSHIP_SETTING',
	SET_TMP_PICKED_MEMBERSHIP_PLAN: 'SET_TMP_PICKED_MEMBERSHIP_PLAN',

	SET_CHANGE_CITY_MODAL: 'SET_CHANGE_CITY_MODAL',
	SET_DIFF_LOCATION_TOOLTIP: 'SET_DIFF_LOCATION_TOOLTIP',
	SET_ALL_ACTIVE_VENDORS: 'SET_ALL_ACTIVE_VENDORS',
	SET_UNCONFIRMED_DELIVERY_ORDER: 'SET_UNCONFIRMED_DELIVERY_ORDER',
	SET_BANNER_PROMOTION: 'SET_BANNER_PROMOTION',
	SET_STUDENT_BANNER_PROMOTION: 'SET_STUDENT_BANNER_PROMOTION',

	SET_ALL_PROMO_BANNERS: 'SET_ALL_PROMO_BANNERS',

	SET_HAS_SPLITS_REQUESTS: 'SET_HAS_SPLITS_REQUESTS',

	SET_SYSTEM_SETTINGS: 'SET_SYSTEM_SETTINGS',
	SET_STUDENT_VERIFY_SETTINGS: 'SET_STUDENT_VERIFY_SETTINGS',

	SET_APP_FEEDBACK_TAGS: 'SET_APP_FEEDBACK_TAGS',
	SET_SHOW_WHERE_HEARD_FEEDBACK_MODAL: 'SET_SHOW_WHERE_HEARD_FEEDBACK_MODAL',

	SET_APP_ANNOUNCE_DATA: 'SET_APP_ANNOUNCE_DATA',
	SET_SHOW_ANNOUNCE_MODAL: 'SET_SHOW_ANNOUNCE_MODAL',

	SET_ALL_FRIENDS: 'SET_ALL_FRIENDS',
	SET_NEW_INVITES: 'SET_NEW_INVITES',
	SET_ACTIVE_ROUTE: 'SET_ACTIVE_ROUTE',
	SET_MESSAGES_BY_CHANNEL: 'SET_MESSAGES_BY_CHANNEL',
};
