ENV['SWIFT_VERSION'] = '5'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

end

target 'Snapfood' do


  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => true,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'RNSound', :path => '../node_modules/react-native-sound'

  # pod 'RNAudio', :path => '../node_modules/react-native-audio'

  # comment the next line to disable credit card scanning
  # pod 'CardIO'


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
react_native_post_install(
  installer,
  config[:reactNativePath],
  :mac_catalyst_enabled => false,
  # :ccache_enabled => true
)
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    #  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
           config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
           config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

      end
    end
  end
end
end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end